name: Azure CI/CD Deploy

on:
  push:
    branches:
      - registration-flow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Вход в Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"d7be29d0-6e34-4281-8eb5-24d4a859ed19","clientSecret":"kHO8Q~pxV.JO44XqjkFTWJJ1V76s7uex4A7UFcwX","tenantId":"6580ee3b-888b-415d-9e29-2154efbc6098","subscriptionId":"ВАШ_ID_ПОДПИСКИ"}'

      - name: Деплой в Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: openai-bot-app-001
          package: .
